### ISSUE TITLE
Performance fixes for Openstack/GCE

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#100]
revisit openstack module for multi instance provisioning since looping in ansible is taking toll on provisioning time. Further changing over to openstack client or python nova with count based provisioning would definitely increase performance .

revisit gcloud gce module for multi instance provisioning since looping in ansible is taking toll on provisioning time.

https://trello.com/c/MX1CaaZB/103-8-ci-provisioning-linch-pin-performance-fixes-openstack-gce-instances

**Comment by samvarankashyap** [comment]
PR #143 PR #141 fixes the issue
