### ISSUE TITLE
linchpin init should not run setup.py or check requirements.txt

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#125]
It appears linchpin init will check requirements.txt (not sure if it's running setup.py or not) and verify the defaults are installed. In addition to not creating a linchpin_config.yml, a check is not necessary.

**Comment by samvarankashyap** [comment]
According to the code (https://github.com/CentOS-PaaS-SIG/linch-pin/blob/master/linchpin.py#L73) 
linchpin init will not check for the requirements.txt , it just creates the required directory structure and renders the linchpin_config.yml (jinja template file with the variables).

**Comment by samvarankashyap** [comment]
According to [setuptools documentation](http://setuptools.readthedocs.io/en/latest/setuptools.html ) its one of the side effects of using console scripts in setup.py. It mentions the effects are : 
- When your project is installed, either by using EasyInstall, setup.py install, or setup.py develop, all of the dependencies not already installed will be located (via PyPI), downloaded, built (if necessary), and installed.
- Any scripts in your project will be installed with wrappers that verify the availability of the specified dependencies at runtime, and ensure that the correct versions are added to sys.path (e.g. if multiple versions have been installed).
- Python Egg distributions will include a metadata file listing the dependencies.
