### ISSUE TITLE
linchpin rise target should be an argument instead of an option

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#128]
Currently, when running linchpin rise, if a particular target is requested, a --target flag must be applied. It makes more sense to just have it be an argument. If no argument is provided, linchpin rise will just attempt to start each target in the PinFile.

Consider the following Pinfile:

`---
ae2e-test:
  topology: simple-ae2e-cluster.yml
  layout: openshift-3node-cluster.yml

e2e:
  topology: simple-e2e-os-cluster.yml
  layout: openshift-3node-cluster.yml
`
Requesting linchpin rise to bring up the **e2e** target should be simple:

`$ linchpin rise e2e`

If both targets are desired:

`$ linchpin rise`

Essentially, eliminate the --target option as it's superfluous.

**Comment by greg-hellings** [comment]
But please make it accept multiple arguments!

**Comment by herlo** [comment]
Fixed by #206
