### ISSUE TITLE
Installing linchpin Python package is noisy

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#133]
Python packages should create at most a small number of high level directories inside of site-packages when they get installed. Currently, running an install of the pip packaging for linch-pin results in the creation of 14 top level directories and one top level file (linchpin.py) which gets built into linchpin.pyc and linchpin.pyo by various install options.

A fifteenth directory gets created that is the .egg-info directory.

All of these directories should, in best practices, be placed under a linchpin/ directory to contain all of the "mess". The easiest way to do this would be to put all the installed directories under a top level linchpin/ directory in the source tree. Alternatively, there is likely a way to just change the setup.py configuration to do so.

**Comment by herlo** [comment]
Agreed. We actually have talked about this and will be moving things this direction very soon. Thanks Greg. I'll add a milestone and such here to get this in place very soon.

**Comment by herlo** [comment]
In my review yesterday, I reworked the packaging and configuration for both the linchpin package, and the cli. It turned out to be a major breaking change, thus we'll be targeting 1.0 for this and it will be implemented at that time.

**Comment by herlo** [comment]
Fixed by #188

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean Python Package](https://trello.com/c/QExbZtAn/2-clean-python-package)
