### ISSUE TITLE
Include license information

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#134]
Please include a LICENSE or COPYING file, or the like, to indicate the license that the code is released under. Such will be necessary for many (all?) downstream packaging efforts.

**Comment by herlo** [comment]
https://github.com/CentOS-PaaS-SIG/linch-pin/commit/0de565699f282df37a3341ec10a10c2ba7602ed8 provided the LICENSE file. Please advise if further requirement is needed.
