### ISSUE TITLE
Linch-pin feedback

### ISSUE THREAD

**Issue by jlebon** [CentOS-PaaS-SIG/linch-pin#147]
Hi all,

Thought I'd give some feedback from an exercise in trying out linch-pin for the first time. I understand a lot of the below is simply due to the project still being in its infancy, though I hope you still appreciate the feedback. :) Sorry in advance for the massive dump of issues in one shot. Some of those may already exist as independent issues.

Major issues:

1. [Documentation](http://linchpin.readthedocs.org/) is incomplete. There are no mentions of essential things like basic CLI usage (e.g. `init`/`rise`/`drop`), the configuration file, credentials, etc... This makes it very hard for beginners to get started.

2. Python packages are not namespaced, so e.g. `library`/`provision`/`outputs` etc... are all dumped directly in `site-packages` rather than e.g. a `linchpin/` dir. Esp. important since most of those are not even actual python modules.

3. Credentials files have to be stored in the vars dir, which is in the bowels of the python site-packages dir.

Minor issues:

1. Inconsistent field naming. E.g. using `res_` in some places and `resource_` in others. (I'd prefer the latter everywhere). Also, it's generally nicer in YAML to use `-` instead of `_`, but that's subjective of course :).

2. Unconditional debug print statements used rather than e.g. a logging module. It makes the output a bit harder to understand.

**Comment by greg-hellings** [comment]
Documentation is a constant work-in-progress. We know we are woefully behind on that. Until about 2 weeks ago we had no docs, so we're trying to make steady progress on that! 

Inconsistent field naming: Can you open a new issue to address this, specifically? This really is a bug and should be captured by some concerted work after a standard is decided upon.

As for the other items you bring up:

The lack of a top level namespace for the Python package components is captured in issue #133 

The credentials problem has been raised before. We are working on a solution to credentials across the board, captured in #76 

Debugging to a log file is already captured by #146

**Comment by jlebon** [comment]
> Documentation is a constant work-in-progress. We know we are woefully behind on that. Until about 2 weeks ago we had no docs, so we're trying to make steady progress on that!

Sounds good. This is by far the biggest issue I encountered.

> Inconsistent field naming: Can you open a new issue to address this, specifically? This really is a bug and should be captured by some concerted work after a standard is decided upon.

OK, I created https://github.com/CentOS-PaaS-SIG/linch-pin/issues/149. I'll close this now, since all the other ones are captured in issues.

Thanks!

**Comment by samvarankashyap** [comment]
@jlebon : Thank you for the feedback . We will working on the fixes. All the issues pointed out will be fixed in no time.
