### ISSUE TITLE
linchpin dependencies packaged for fedora/CentOS

### ISSUE THREAD

**Issue by dustymabe** [CentOS-PaaS-SIG/linch-pin#170]
It would be great to have some packages for linchpin in Fedora/CentOS. I realize that linchpin might not be ready yet, which is fine. Even if it's not ready I'd like to use this issue to track the progress of making packages available.

Thanks for the hard work!

**Comment by greg-hellings** [comment]
I'm currently working on packaging some required Python dependencies, after
which I'll get on to packaging linch-pin.

**Comment by herlo** [comment]
@greg-hellings can I be co-maintainer? :1st_place_medal:

**Comment by herlo** [comment]
Package reviews are up. If you are a packager, please take a moment to review these packages:

* linchpin: https://bugzilla.redhat.com/show_bug.cgi?id=1441843
* python-yamlordereddictloader: https://bugzilla.redhat.com/show_bug.cgi?id=1441842
* python-camel: https://bugzilla.redhat.com/show_bug.cgi?id=1441841

**Comment by greg-hellings** [comment]
All the deps are packaged, but the reviewer for linchpin itself wants to wait until 1.0 because of all the extra noise dropped into site-packages by the 0.9.1 release.

**Comment by herlo** [comment]
Split this into two tasks. See #240 for the linchpin RPM package itself.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce Dependencies / Multiple Packages](https://trello.com/c/e9Yr6e1R/16-reduce-dependencies-multiple-packages)
