### ISSUE TITLE
linchpin provision beaker machine with example topology fails with error missing required property

### ISSUE THREAD

**Issue by smatula** [CentOS-PaaS-SIG/linch-pin#171]
Linchpin fails with missing required property 'res_defs' trying to provision a beaker machine using example beaker topology.

PLAY [including the configuration files] ***************************************

TASK [Include linchpin_config] *************************************************
ok: [localhost] => (item=/usr/linchpin_config.yml)

PLAY [schema check and Pre Provisioning Activities  on topology_file] **********

TASK [common : DEBUG: topology and schema] *************************************
ok: [localhost] => {
    "msg": "topology: /root/sjm-run-test/topologies/beaker.yml schema: /root/linchpin/lib/python2.7/site-packages/ex_schemas/schema_v2.json"
}

TASK [common : schema check for given topology file] ***************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"content": {"error": "u'res_defs' is a required property", "status": false}, "path": "/root/sjm-run-test/topologies/beaker.yml"}}
	to retry, use: --limit @/root/linchpin/lib/python2.7/site-packages/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

---
topology_name: beaker
resource_groups:
  - resource_group_name: test1
    res_group_type: beaker
    job_group: ci-ops-central
    recipesets:
      - distro: RHEL-6.5
        arch: x86_64
        arches:
          - X86_64
          - X86_64
        keyvalue:
          - MEMORY>1000
          - DISKSPACE>20000
        hostrequire:
          - arch=X86_64
        count: 1

**Comment by smatula** [comment]
Running using cli linchpin version 0.9.0

**Comment by samvarankashyap** [comment]
@greg-hellings @herlo : Ping

**Comment by robled** [comment]
I'm looking at this issue, please assign it to me.  I don't appear to have the necessary permissions on this project to assign it to myself.

**Comment by robled** [comment]
After some debugging I believe that this is a schema version issue.  The v2 schema will produce this error, but the v3 schema will not.  In your **/usr/linchpin_config.yml** file please change the **schema:** value from **schema_v2.json** to **schema_v3.json** and test again.  With the v3 schema in place, your Beaker topology file should look like the [example](https://github.com/CentOS-PaaS-SIG/linch-pin/blob/develop/examples/topology/beaker_server.yml) here.

Out of curiosity, how was **/usr/linchpin_config.yml** installed on your system?  Was it put there manually by any chance?

**Comment by robled** [comment]
@herlo @samvarankashyap 

When installing linchpin 0.9.0 from pypi, there are **two** config files produced by the package, and one of them refers to schema_v2, while the other refers to schema_v3.  Which schema is correct to use with linchpin 0.9.0?  Certainly if you're using Beaker you want to use schema_v3.  

I know that the linchpin code searches a lot of paths to find the config file, and from my end it seems like the package should only place a single config file on the filesystem, therefore avoiding any unexpected behaviors such as this.  What do you think?  Here's some copypasta to prove my theory:

```
(linchpin) [vagrant@localhost linchpin]$ pwd
/home/vagrant/.virtualenvs/linchpin

(linchpin) [vagrant@localhost linchpin]$ find . -name 'linchpin_config.yml'
./linchpin_config.yml
./lib/python2.7/site-packages/tests/playbooks/linchpin_config.yml

(linchpin) [vagrant@localhost linchpin]$ cat linchpin_config.yml
---
keystore_path: "{{ playbook_dir }}/../keystore"
outputfolder_path: "{{ playbook_dir }}/../outputs"
inventoryfolder_path: "{{ playbook_dir }}/../inventory"
# inventory playbooks are not necessary because inventory_type specific tasks are defined in inventory_gen role
inventory_playbooks:
  - duffy_inventory.yml
async: false
async_timeout : 1000
no_output : false
schema: "{{ playbook_dir }}/../ex_schemas/schema_v3.json"
inventory_layouts_path: "{{ playbook_dir }}/../inventory_layouts"
inventory_outputs_path: "{{ playbook_dir }}/../inventories"
inventory_types:
  - "aws"
  - "gcloud"
  - "openstack"
  - "duffy"
  - "beaker"
  - "generic"
check_mode: no

(linchpin) [vagrant@localhost linchpin]$ cat ./lib/python2.7/site-packages/tests/playbooks/linchpin_config.yml
---
keystore_path: "keystore"
outputfolder_path: "outputs"
inventoryfolder_path: "inventory"
# inventory playbooks are not necessary because inventory_type specific tasks are defined in inventory_gen role
inventory_playbooks:
  - duffy_inventory.yml
async: false
async_timeout : 1000
no_output : false
schema: "ex_schemas/schema_v2.json"
inventory_layouts_path: "inventory_layouts"
inventory_outputs_path: "inventory_outputs"
inventory_types:
  - "aws"
  - "gcloud"
  - "openstack"
  - "generic"
```

**Comment by herlo** [comment]
David,

You are correct. You should be using schema_v3. I'm sorry I didn't respond
earlier, I've been out sick for the past few days. Thanks for following up
on this. I'll fix this and patch it as soon as possible.

herlo

**Comment by herlo** [comment]
To address the original issue. I'm not sure how the OP was able to put linchpin_config.yml in /usr/. In future versions, we'll have a well-defined set of paths where linchpin_config.yml can reside. With one default residing in a common place. I suspect it will look in the following order only.

* ./.linchpin_config.yml
* ~/.linchpin_config.yml
* /etc/linchpin/linchpin_config.yml (If installed via rpm/dpkg/etc)
* /python/path/linchpin/linchpin_config.yml (defaults which should work without change)

Anyway, I think the OP just simply needs to either update or remove the /usr/linchpin_config.yml file and retry. If that doesn't work, please follow up here. I will give this some time for response before closing the issue.

**Comment by smatula** [comment]
linchpin_config.yml created using linchpin config command. Did not change the schema. Could not get linchpin rise to run until I moved the the config file to /usr.

The following output is if config file removed from /usr/
(linchpin)[root@sjm-rhel-73-server-released-lp-5 sjm-test-lp]# linchpin rise
debug:: searching linchpin_config file from path :: 
/root/sjm-test-lp/linchpin_config.yml
debug:: File found returning ::
/root/sjm-test-lp/linchpin_config.yml
debug:: searching linchpin_config file from path :: 
/root/sjm-test-lp/linchpin_config.yml
debug:: File found returning ::
/root/sjm-test-lp/linchpin_config.yml
debug::print file path
/root/sjm-test-lp/linchpin_config.yml
Finding topology in local folder ./topology
debug:: searching linchpin_config file from path :: 
/root/sjm-test-lp/linchpin_config.yml
debug:: File found returning ::
/root/sjm-test-lp/linchpin_config.yml
debug::print file path
/root/sjm-test-lp/linchpin_config.yml
Finding layout in local folder ./layouts
{'linchpin_config': '/root/sjm-test-lp/linchpin_config.yml', 'inventory_layout_file': '/root/sjm-test-lp/layouts/rhevm.yml', 'state': 'present', 'outputfolder_path': '/root/sjm-test-lp/outputs', 'inventory_outputs_path': '/root/sjm-test-lp/inventories', 'topology': '/root/sjm-test-lp/topologies/rhevm.yml'}
debug:: module path ::/root/linchpin/lib/python2.7/site-packages/library

PLAY [including the configuration files] ***************************************

TASK [Include linchpin_config] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
	to retry, use: --limit @/root/linchpin/lib/python2.7/site-packages/provision/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1  


Will manually update schema to 3 and try with update topology.

**Comment by smatula** [comment]
linchpin installed with pip

**Comment by smatula** [comment]
Changing schema to v3 works and solves this issue.

**Comment by herlo** [comment]
I apologize for the inconvenience. I'll double check the output of linchpin config  and make sure it provides schema_v3 correctly.

@herlo

**Comment by herlo** [comment]
I just installed 0.9.0 and performed a linchpin config --init and it works fine. If you, however, do a linchpin config --reset, it does indeed generate a schema_v2.json. I'm reopening this and addressing it asap.
