### ISSUE TITLE
Missing dependency for python-krbV

### ISSUE THREAD

**Issue by robled** [CentOS-PaaS-SIG/linch-pin#177]
This package is needed for Beaker provisioning.

```
TASK [beaker : provision beaker systems] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named krbV
```

**Comment by robled** [comment]
Please ignore the first commit in this ticket - I had to adjust my git workflow to accommodate the new 'develop' branch.

**Comment by herlo** [comment]
Approaching this differently now. Please view extras_require section in the setup.py as an example.
