### ISSUE TITLE
linchpin cannot find linchpin_config.yml - Looks to be bug in site.yml

### ISSUE THREAD

**Issue by smatula** [CentOS-PaaS-SIG/linch-pin#181]
When running linchpin, initially finds the linchpin_config.yml. When playbook (including the configuration files) is run to include configuration files. Playbook cannot fine linchpin_config.yml.

Looks like site.yml has bugs.
../linchpin/lib64/python2.7/site-packages/provision/site.yml
excerpt:
      with_first_found:
        - "{{ linchpin_config.yml | default(omit) }}"
        - "../linchpin_config.yml"
        - "~/.linchpin_config.yml"
        - "/usr/linchpin_config.yml"
        - "/etc/linchpin/linchpin_config.yml"

Should first line after with_first_found:  not be
   - "{{ linchpin_config | default(omit) }}"

Should line "~/.linchpin_config.yml" not be
   - "~/linchpin_config.yml" 

The line  - "../linchpin_config.yml"  is not finding file also. Have not found the reason why yet.

**Comment by smatula** [comment]
linchpin version 0.9.0 installed by pip

**Comment by herlo** [comment]
The ../linchpin_config.yml would be relative to the location of the running site.yml. In this case, that's provision/site.yml. Thus, the linchpin_config.yml would need to be at the base of the linch-pin directory to work properly. If this is installed via pip, that would be `/path/to/python/site-packages/`. It's completely counterintuitive, and should really be fixed. 

We are addressing this issue directly in 1.0.0. To that end, you can use `linchpin config --reset` and place the generated linchpin_config.yml in the appropriate directory for now.  Sorry for this inconvenience.

@herlo

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Context Manager](https://trello.com/c/DMjTag2G/3-context-manager)
