### ISSUE TITLE
(2) Enhancement Request - Set Beaker Jobs Whiteboard value.

### ISSUE THREAD

**Issue by smatula** [CentOS-PaaS-SIG/linch-pin#182]
Have field in topology or auto generate name to be set as beaker jobs whiteboard value. Name should be a descriptive name that one can easily tell the linchpin provision job that started the beaker job. 

The whiteboard is a free-form string to describe the job or recipe. It looks like I the whiteboard for the recipe can be set using the following property:
         whiteboard: "<value>"
   under recipesets:

   In beaker whiteboard is one of the fields displayed when listing jobs. When linchpin provisions a beaker machine the whiteboard field is blank. 

I think the job whiteboard can be passed as an option when creating the beaker job.

**Comment by herlo** [comment]
I believe this is a general concept we've been working for all providers in linch-pin. I'd like to combine this with #148. Thanks!
