### ISSUE TITLE
(5) OpenShift Provision Target

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#198]
Add support for provisioning containers and other resources in an OpenShift instance alongside existing providers.

**Comment by robled** [comment]
I see that the milestone for this is currently v1.1.0.  Is there anything my team can do to get this included in v1.0.0?

**Comment by herlo** [comment]
Does #203 close this issue?

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [New Providers](https://trello.com/c/Y2AFZuCw/1-new-providers)
