### ISSUE TITLE
(1) Relax dependency pinning as much as possible

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#204]
Some packages are pinned with absolute versions (e.g. beaker-client==23.3, ansible==2.2.1.0, etc). These should be relaxed as much as possible, hopefully down to >= dependencies.

Packaging linchpin for distros will feature interruptions to usability if exact versions are pinned in places and then those update from the underlying package manager.

**Comment by samvarankashyap** [comment]
Ansible has recently released , 2.3 on pypi . I need check whether linchpin works fine w.r.to 2.3 release.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce Dependencies / Multiple Packages](https://trello.com/c/e9Yr6e1R/16-reduce-dependencies-multiple-packages)
