### ISSUE TITLE
(3) Document the new cli workflow

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#208]
Variables and user documentation are needed, plus more cleanup and such.

**Comment by herlo** [comment]
This is in reference to PR #206

**Comment by seandst** [comment]
A lot of this appears to be done in the PR; I can pick up the task of bringing those PR notes into the sphinx docs and validating them.

**Comment by herlo** [comment]
@seandst that's exactly the plan here. Something simple like a getting started guide. And then maybe a page describing inputs vs config options, how to use them, and such. Feel free to ask any questions you have.  We do have #linchpin on freenode now too, so if you want to join there, that may be helpful to you as well.
