### ISSUE TITLE
(8) Write tests for the new develop tree

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#209]
The jjb should be similar to what we already have. The tests themselves will likely differ greatly.

**Comment by robled** [comment]
In the cinch project we are using codecov.io for coverage reports.  See this PR for an implementation example for that as well as some basic unit tests running in Travis:

https://github.com/RedHatQE/cinch/pull/74

**Comment by herlo** [comment]
Resolved by #242. More to come, see #247

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic Unit Tests](https://trello.com/c/WCG8WGsg/4-basic-unit-tests)
