### ISSUE TITLE
Add missing functionalites due to PR #206

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/linch-pin#210]
Summary:
The following operations are being commented out in the PR #206 . 

- linchpin invgen  # generates inventories based on outputs, layouts
- linchpin validate # validates topology files
- linchpin topology get # fetches topologies from both local , and github repo 
- linchpin layout get  # fetches layouts from both local and github repo .

These above functionalities should be rewritten according to the changes proposed in #206

**Comment by herlo** [comment]
This bug already exists as #92, closing.
