### ISSUE TITLE
Returned results from API calls (up and destroy) when console set to False does not contain failures. 

### ISSUE THREAD

**Issue by smatula** [CentOS-PaaS-SIG/linch-pin#226]
Set console to failure. 
Use api to perform up or destroy. Have a setup that will fail. Incorrect authentication value etc...
Results returned only for tasks that were OK. The failed task information is not returned.

PlaybookCallback() method is only capturing v2_runner_on_ok.  Needs to be updated.
 
Should add v2_runner_on_failed also.  Append failed result to results also.

    def v2_runner_on_failed(self, result, **kwargs):

        """Save result instead of printing it"""

        self.results.append(result)

linchpin version 1.0.0a4

**Comment by herlo** [comment]
The API call 'lp_rise()' is deprecated, consider using 'lp_up'.

**Comment by herlo** [comment]
Thank you for identifying this issue. A patch will be coming very soon.

**Comment by herlo** [comment]
@smatula If you have a moment, feel free to review this issue. I've added you to our collaborators group, so you should be able to give feedback.

**Comment by herlo** [comment]
Fixed by #224
