### ISSUE TITLE
Need a way to retrieve the path to credential store

### ISSUE THREAD

**Issue by gsr-shanks** [CentOS-PaaS-SIG/linch-pin#229]
We would want to have a way for a user to store/retrieve credentials programmatically and have this value set in assoc_creds of the topology file.

Refer https://url.corp.redhat.com/776ec8f

**Comment by herlo** [comment]
@gsr-shanks Referring you to #76 and any related PRs around this concept.

**Comment by samvarankashyap** [comment]
@gsr-shanks @herlo  Hope the recent PR #236  fixes this issue . If so we can close it.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Credentials Management / Authentication Driver](https://trello.com/c/2z88W2CT/6-credentials-management-authentication-driver)
