### ISSUE TITLE
(3) Document ansible vars from PR #206

### ISSUE THREAD

**Issue by seandst** [CentOS-PaaS-SIG/linch-pin#230]
The description of https://github.com/CentOS-PaaS-SIG/linch-pin/pull/206#issue-222544291 (starting with the "INPUTS" heading) contains docs related to the ansible vars used by linchpin that might be useful to users, and should probably be included in the docs on the develop branch.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improved documentation](https://trello.com/c/C7OBVZFe/8-improved-documentation)
