### ISSUE TITLE
(3) Hook up the travis and jjb for the develop tree

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#239]
See #209 for reference. But essentially this needs to run those tests in jenkins and/or travis as applicable.

**Comment by samvarankashyap** [comment]
@herlo : can we close this issue as travis is already in place? we can have another issue for jjb .

**Comment by herlo** [comment]
@samvarankashyap sure, I'll close it and open one for integration tests and jenkins jobs.

**Comment by herlo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Basic Unit Tests](https://trello.com/c/WCG8WGsg/4-basic-unit-tests)
