### ISSUE TITLE
Regression introduced in schema_check.py

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#59]
https://github.com/CentOS-PaaS-SIG/linch-pin/blob/master/library/schema_check.py#L82

In previous versions of schema_check.py, this check either did not happen, or it didn't require the resource_group_vars object.

This commit introduced an apparent regression:

https://github.com/CentOS-PaaS-SIG/linch-pin/commit/6b72cb45d3d2455c6fccd67dff0865ed40ee6e99

When you create a topology similar to this: 

---
topology_name: "duffy_single" # topology name
resource_groups:
  -
    resource_group_name: "duffy_single"
    res_group_type: "duffy"
    res_defs:
      -
        res_name: "duffy_nodes"
        res_type: "duffy"
        version: 7
        arch: "x86_64"
        count: 1
    assoc_creds: "duffy_creds"

And run the latest version of linch-pin against it as such:

ansible-playbook -vvv ~/Projects/linch-pin/provision/site.yml -e "state=present schema='~/Projects/linch-pin/ex_schemas/schema_v2.json' topology='~/Projects/paas-ci/config/topologies/duffy-single.yml'"

The result is:

..snip..
TASK [common : schema check for given topology file] ***************************
task path: /home/sig-paas/Projects/linch-pin/provision/roles/common/tasks/main.yml:3
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: sig-paas
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1473372193.46-270600084285347 `" && echo ansible-tmp-1473372193.46-270600084285347="` echo $HOME/.ansible/tmp/ansible-tmp-1473372193.46-270600084285347 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp7KFPLd TO /home/sig-paas/.ansible/tmp/ansible-tmp-1473372193.46-270600084285347/schema_check
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /home/sig-paas/sandbox/linch-pin-testing/bin/python /home/sig-paas/.ansible/tmp/ansible-tmp-1473372193.46-270600084285347/schema_check; rm -rf "/home/sig-paas/.ansible/tmp/ansible-tmp-1473372193.46-270600084285347/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_nlBZs1/ansible_module_schema_check.py", line 125, in <module>
    main()
  File "/tmp/ansible_nlBZs1/ansible_module_schema_check.py", line 114, in main
    validate_values(module,data_file_path)
  File "/tmp/ansible_nlBZs1/ansible_module_schema_check.py", line 95, in validate_values
    status = validate_grp_names(data)
  File "/tmp/ansible_nlBZs1/ansible_module_schema_check.py", line 82, in validate_grp_names
    res_grp_vars = data['resource_group_vars']
KeyError: 'resource_group_vars'

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "schema_check"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_nlBZs1/ansible_module_schema_check.py\", line 125, in <module>\n    main()\n  File \"/tmp/ansible_nlBZs1/ansible_module_schema_check.py\", line 114, in main\n    validate_values(module,data_file_path)\n  File \"/tmp/ansible_nlBZs1/ansible_module_schema_check.py\", line 95, in validate_values\n    status = validate_grp_names(data)\n  File \"/tmp/ansible_nlBZs1/ansible_module_schema_check.py\", line 82, in validate_grp_names\n    res_grp_vars = data['resource_group_vars']\nKeyError: 'resource_group_vars'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

The schema_check.py library should allow an *optional* resource_group_vars object, but not require it.

**Comment by herlo** [comment]
Bump

**Comment by samvarankashyap** [comment]
PR [#62](https://github.com/CentOS-PaaS-SIG/linch-pin/pull/62) addresses the above issue
