### ISSUE TITLE
ImportError: No module named InventoryFilters

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#64]
It looks like recent code introduced this issue.

See the log at: 
https://ci.centos.org/job/origin-from-source-0-test-matrix/PYTHON=system-CPython-2.7,TOPOLOGY=duffy-3node-cluster,nodes=paas-sig-ci-slave01/102/console

**Comment by samvarankashyap** [comment]
Working on it .
Upcoming PR might resolve the error, It might be the same path resolution issue !

**Comment by herlo** [comment]
@samvarankashyap did PR #65 fix this issue?

**Comment by herlo** [comment]
fixed with PR #65
