### ISSUE TITLE
Feature Request: CLI honors standard path env variable for configuration files, etc.

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#70]
Make sure the command line tool can find the configurations in a standard path. 

The idea is that the linchpin_config.yml might be found in some standard locations. For example:

/etc/linchpin/linchpin_config.yml
~/.linchpin_config.yml
./linchpin_config.yml
etc.

Thus, make a standard env variable or somesuch that gets set either by installation or configuration to ensure the configuration files can be located easily and in predictable locations.

**Comment by samvarankashyap** [comment]
PR #77 fixes the issue

**Comment by herlo** [comment]
@samvarankashyap can you point to the place where this is resolved in that PR? I don't see it as we don't yet have a CLI.

**Comment by samvarankashyap** [comment]
The order of resolving config file is fixed in the following file 
https://github.com/CentOS-PaaS-SIG/linch-pin/blob/212c72e153ab3d070002ba0b84300f48b81049f1/provision/site.yml

**Comment by herlo** [comment]
I think you mean PR #72 - https://github.com/CentOS-PaaS-SIG/linch-pin/pull/72/files#diff-606277c22a951f9d2e56a00578ee523fR2
