### ISSUE TITLE
'shade is required for this module' error when provisioning openstack from venv

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#71]
Created a virtualenv, installed shade with pip.

    (venv)[herlo@x99 venv]$ pip show shade
    You are using pip version 6.0.8, however version 8.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    ---
    Name: shade
    Version: 1.12.1
    Location: /home/herlo/Projects/venv/lib/python2.7/site-packages
     Requires: python-keystoneclient, python-cinderclient, python-magnumclient, requestsexceptions, munch, jsonpatch, python-ironicclient, python-novaclient, six, netifaces, python-swiftclient, python-troveclient, python-glanceclient, python-neutronclient, pbr, ipaddress, os-client-config, keystoneauth1, dogpile.cache, decorator, python-designateclient, python-heatclient

When I run the ansible-playbook for linch-pin, I get the following output:

    (venv)[herlo@x99 venv]$ ansible-playbook -vvv ~/Projects/centos/git/linch-pin/provision/site.yml -e "state=present topology='~/Projects/centos/git/paas-ci/config/topologies/openstack-3node-cluster.yml'"
    Using /etc/ansible/ansible.cfg as config file
     [WARNING]: provided hosts list is empty, only localhost is available
    
    ..snip..
    
    TASK [openstack : provision/deprovision os_server resources by looping on count] ***
    task path: /home/herlo/Projects/centos/git/linch-pin/provision/roles/openstack/tasks/provision_os_server.yml:5
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: herlo
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475686934.36-264020423014197 `" && echo ansible-tmp-1475686934.36-264020423014197="` echo $HOME/.ansible/tmp/ansible-tmp-1475686934.36-264020423014197 `" ) && sleep 0'
    <127.0.0.1> PUT /tmp/tmpz1rYPT TO /home/herlo/.ansible/tmp/ansible-tmp-1475686934.36-264020423014197/os_server
    <127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python2 /home/herlo/.ansible/tmp/ansible-tmp-1475686934.36-264020423014197/os_server; rm -rf "/home/herlo/.ansible/tmp/ansible-tmp-1475686934.36-264020423014197/" > /dev/null 2>&1 && sleep 0'
    failed: [localhost] (item=None) => {"failed": true, "instance": ["", "", "", "", "present", "rhel-6.5_jeos", "ci-factory", "m1.small", "e2e-openstack", "os", "ha_inst", 0], "invocation": {"module_args": {"api_timeout": 99999, "auth": {"auth_url": "", "password": "", "project_name": "", "username": ""}, "auth_type": null, "auto_ip": true, "availability_zone": null, "boot_from_volume": false, "boot_volume": null, "cacert": null, "cert": null, "cloud": null, "config_drive": false, "endpoint_type": "public", "flavor": "m1.small", "flavor_include": null, "flavor_ram": null, "floating_ip_pools": null, "floating_ips": null, "image": "rhel-6.5_jeos", "image_exclude": "(deprecated)", "key": null, "key_name": "ci-factory", "meta": null, "name": "os_ha_inst_0", "network": "e2e-openstack", "nics": [], "region_name": null, "scheduler_hints": null, "security_groups": ["default"], "state": "present", "terminate_volume": false, "timeout": 180, "userdata": null, "verify": true, "volume_size": false, "volumes": [], "wait": true}, "module_name": "os_server"}, "msg": "shade is required for this module"}
    
    NO MORE HOSTS LEFT *************************************************************
    	to retry, use: --limit @/home/herlo/Projects/centos/git/linch-pin/provision/site.retry
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=20   changed=1    unreachable=0    failed=1

**Comment by samvarankashyap** [comment]
PR #72 fixes the issue

**Comment by herlo** [comment]
I don't think adding shade to the requirements.txt resolves this issue.

I've got shade installed inside the virtualenv.

    (venv)[herlo@x99 venv]$ ipython
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    Python 2.7.11 (default, Sep  2 2016, 14:51:16) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 3.2.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import shade
    
    In [2]:

------------------
Outside the venv, you can see that shade isn't installed

    [herlo@x99 ~]$ ipython
    Python 2.7.11 (default, Sep  2 2016, 14:51:16) 
    Type "copyright", "credits" or "license" for more information.
    
    IPython 3.2.1 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    
    In [1]: import shade
    ---------------------------------------------------------------------------
    ImportError                               Traceback (most recent call last)
    <ipython-input-1-70e47b970de7> in <module>()
    ----> 1 import shade
    
    ImportError: No module named shade

------

I think the problem might be that I don't have linch-pin checked out into the venv. I didn't do this previously, however, and it worked just fine. That was, a centos7.3 system, however. This one is fedora 23 x86_64.

**Comment by samvarankashyap** [comment]
Note for future reference : 
When using ansible playbooks in a virtual environment . 
ansible_python_interpreter variable needs to be set in ansible.cfg or hosts file as follows 
```
ansible_python_interpreter="/usr/bin/env python" 
```
