### ISSUE TITLE
requirements.txt is not installable

### ISSUE THREAD

**Issue by greg-hellings** [CentOS-PaaS-SIG/linch-pin#95]
It is not possible to run a basic pip install of the requirements.txt file as it exists in the repository at present.

Steps to reproduce:
1. Clone linch-pin
2. Create and activate new virtualenv
3. Execute "pip install -r requirements.txt" from the linch-pin directory

Expected result:
Pip should install all necessary packages

Actual result:
Pip exits with the following error message
Collecting python-openstackclient==0.8.6 (from -r requirements.txt (line 18))
  Could not find a version that satisfies the requirement python-openstackclient==0.8.6 (from -r requirements.txt (line 18)) (from versions: 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.3.0)
No matching distribution found for python-openstackclient==0.8.6 (from -r requirements.txt (line 18))

**Comment by herlo** [comment]
The latest merged should have python-openstack without a version. I wonder if you are at the latest?

https://github.com/CentOS-PaaS-SIG/linch-pin/blob/master/requirements.txt

**Comment by greg-hellings** [comment]
It appears that commit from last week fixed the problem. Thanks!

**Comment by herlo** [comment]
Great! Closing the issue.
