### ISSUE TITLE
Tracking bug for openstack os_server issue

### ISSUE THREAD

**Issue by herlo** [CentOS-PaaS-SIG/linch-pin#99]
The following bug affects floating IPs on linch-pin since it depends on shade.

https://github.com/ansible/ansible-modules-core/issues/1981

On our trello board here: https://trello.com/c/mfwC3TmE/107-5-ci-provisioner-linch-pin-look-into-floating-ip-bug

Now in code review: https://review.openstack.org/#/c/393884

**Comment by herlo** [comment]
According to the review, the fix was merged Nov 8, 2016 https://review.openstack.org/#/c/393884. Waiting on verification from upstream ansible bug

**Comment by johnbieren** [comment]
https://github.com/ansible/ansible/issues/19613

**Comment by samvarankashyap** [comment]
#126  fixes the current issue
